import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { RigidBody } from "@react-three/rapier"

/**
 * House 
 */
// const HouseX = (props) => 
// {
//     const { nodes, materials } = useGLTF("./assets/models/world/house.glb")
//     return (
//         <RigidBody
//             type="fixed"
//             colliders="hull"
//         >
//             <group {...props} dispose={null}>
               
//             </group>
//         </RigidBody>
//     )
// }


/**
 *  Massive snow
 */
const Snow1 = (props) => 
{
    const { nodes, materials } = useGLTF("./assets/models/world/snow-1.glb")
    return (
        <RigidBody
            type="fixed"
            colliders="trimesh"
        >
            <group {...props} dispose={null}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1586283693.geometry}
                    material={materials.mat21}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group790242002.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1374248848.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1670661091.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group541698014.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group801348135.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group818719132.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group655075396.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1594928605.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group137237167.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group519686499.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1425655452.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1041836491.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1209576230.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group140002579.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group955683139.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1755980947.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1991415909.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group38754262.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group6855632.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group645997890.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group123473807.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group2080916479.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1173577113.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group689519292.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group2129094907.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1438308884.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group992904292.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1929589673.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1562036042.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1774369687.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group976509203.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group138354598.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group716030396.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1420562999.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1672788697.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group857139440.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1214124074.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group2109192676.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group139818712.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group519372889.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group699407553.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group209575811.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group142189506.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group290537018.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group997768220.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group248502027.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group2081116217.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group662371440.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1943753349.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group672329709.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1665403453.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group122861899.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1849800460.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1624930919.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group405830781.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group546435267.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group624269700.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group167675119.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1295451407.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group771054755.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1073474080.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group47673139.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group696470313.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1198287974.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1006892451.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1023881678.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1754512832.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group303232252.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1759290697.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group842498124.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1501278767.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group62955079.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1556504560.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group364810111.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group780592809.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group491702076.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1511047989.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1536362667.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group666905252.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1110043970.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group160570910.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group605995530.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group43305440.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group326579883.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1972280471.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group2012996808.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group978253987.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group339776510.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group610599142.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1830562487.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group10757145.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1899218596.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group161787529.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group45234167.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group509961305.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group284376145.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group635469221.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group207866165.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1607811699.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group60868717.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1726246120.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group326222997.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1401194995.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1622696322.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group350451976.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group470119567.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group753065250.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1728772050.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1701325267.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group2042230979.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group927267243.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group744555488.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group198741331.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group203962996.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1065516475.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group82517478.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group5812108.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group2115839670.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group2026847413.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group613866394.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group2058678388.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1006583961.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1198508694.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group854642489.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1567880503.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group109473454.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group2010307444.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1792915442.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group303833075.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1980829699.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group982449189.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group315248071.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1620177123.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group274486625.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group948376447.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1392060942.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group400651121.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1418382382.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1081543914.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group283182389.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group668469993.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1982470476.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group580982378.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group783005847.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group693775720.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1203027822.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group132429362.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1150842215.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1564146270.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1531245124.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group91400719.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group472168937.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group288297035.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1995692365.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group653383681.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1525600486.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group758384577.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1110862186.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group353718718.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group270538316.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group994015629.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group71219839.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group2097432340.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group283803336.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group64821623.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group294663954.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group242649612.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group56496758.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group464893322.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group730433179.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1183451249.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group585039708.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1990786913.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1164248790.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group267765356.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1943984688.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group514682428.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1399357338.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1548312928.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group588988203.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group1798602863.geometry}
                    material={materials.mat18}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.group423818086.geometry}
                    material={materials.mat18}
                />
            </group>
        </RigidBody>
    )
}



/**
 *  https://poly.pizza/m/jLjH1jMIpH
 */
const StonePlatform = (props) => 
{
    const { nodes, materials } = useGLTF("./assets/models/world/stone-platform.glb")
    return (
        <RigidBody
            type="fixed"
            colliders="hull"
        >
            <group {...props} dispose={null}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.StonePlatform_Cylinder.geometry}
                    material={materials["Material.001"]}
                />
            </group>
        </RigidBody>
    )
}




export default function Platforms()
{
    return(
        <>  
            {/* Base platform */}
            <Snow1 position={ [ 0, 0, 0 ] } scale={ 100 } rotation-y={ 0 } />
        </>
    )
}

useGLTF.preload("./assets/models/world/snow-1.glb")
